version: '3.8'
services:
  mysite:
    build: 
      context: ./mysite
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: letschat
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "9091:80"
