# Generated by Django 4.2 on 2023-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luxmart", "0002_sign_up_car_car_image_alter_car_speed"),
    ]

    operations = [
        migrations.RemoveField(model_name="car", name="speed",),
        migrations.AddField(
            model_name="car", name="car_details", field=models.TextField(default=500),
        ),
    ]
