# Generated by Django 4.2 on 2023-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luxmart", "0003_remove_car_speed_car_car_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car", name="car_details", field=models.TextField(),
        ),
    ]
